name: Build app

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build for Android
        run: |
          cd booklog_manager
          flutter build appbundle

      - name: Upload to Deploygate
        run: |
          curl \
            --url "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps" \
            -H "Authorization: Bearer ${{secrets.DEPLOYGATE_API_KEY}}" \
            -X POST \
            -F "file=@booklog_manager/build/app/outputs/bundle/release/app-release.aab" \
            --form-string "distribution_name=$GIT_BRANCH" \
            --form-string "release_note=Build from Github actions" \
            --form-string "message=git:$GIT_HASH"
